### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Nikronic**
Fixing minor typos and grammatical problems and change paths to relative links.
Also, formatting implemented methods using ` mark.

### CODE REVIEW

**Comment by Nikronic** [comment]
@YU-Zhiyang 
I did not check the implementation yet; are those bold functions implemented?

**Comment by hityzy1122** [comment]
> Fixing minor typos and grammatical problems and change paths to relative links.
> Also, formatting implemented methods using ` mark.

Thank you very very very much!

**Comment by hityzy1122** [comment]
> @YU-Zhiyang
> I did not check the implementation yet; are those bold functions implemented?

Yes, and the bold functions are additional methods which do not exist in the official torchvision module

**Comment by Nikronic** [comment]
No problem, thanks for merging the PR. I thought the bolded ones are not implemented yet. So I think it would be better to format them using ` marker too but a * or something like that to demonstrate that they do not exist in the official PyTorch Transforms package.
What do you think? @YU-Zhiyang 

In the end I think we could set up Github Actions for this repo to make sure any commit is passing tests using CI tools. If you are ok with this, we can follow furthur information in another issue then I can make a PR for that too.

**Comment by hityzy1122** [comment]
> No problem, thanks for merging the PR. I thought the bolded ones are not implemented yet. So I think it would be better to format them using ` marker too but a * or something like that to demonstrate that they do not exist in the official PyTorch Transforms package.
> What do you think? @YU-Zhiyang
> 
> In the end I think we could set up Github Actions for this repo to make sure any commit is passing tests using CI tools. If you are ok with this, we can follow furthur information in another issue then I can make a PR for that too.

Sorry for the late reply, as I am busy seeking for an opportunity of internship. Thanks for all your advice which makes sense. As I am not so familiar with the Github Action and CI tools, I can't set up it currently, I will have a try when I have time. Thanks again!

**Comment by Nikronic** [comment]
No problem, I will handle it in issue #8 and make a PR when it is ready.

**Pull request merged**
